# AppVeyor.com is a Continuous Integration service to build and run tests under Windows
# This yml file was made in part by looking at the yml files for conda and astropy.

# This is not a .NET project, so we build SpiceyPy in the install step.
build: off

environment:
  global:
      WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\windows_sdk.cmd"
  PYPI_PASSWORD:
    secure: put-it-here

  matrix:
      - PYTHON: "C:\\Python37-x64"
        PYTHON_VERSION: "3.7.x"
        ARCH: "64"
        WINDOWS_SDK_VERSION: "v7.1"
        PLAT_NAME: "win-amd64"
        PY_TAG: "cp37"

platform:
  - x64

cache:
  - C:\Users\appveyor\Downloads -> setup.py

install:
  # Log out the python version just so we know it
  - ECHO "%PYTHON_VERSION%"

  # update path to use installed pip
  - set PATH=%PYTHON%\\scripts;%PATH%

  # Download things we absolutely need
  - pip install wheel twine six pytest
  - pip install numpy

  # Now install
  - IF "%ARCH%"=="32" (call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86) ELSE (ECHO "64bit build")
  - IF "%ARCH%"=="64" (call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" amd64) ELSE (ECHO "32bit build")
  - "%PYTHON%/python setup.py install"

  - ECHO "Installed!"
  - "%PYTHON%/Scripts/py.test --version"

test_script:
  - "%PYTHON%/Scripts/py.test bounter/tests"

after_test:
  - ECHO "DONE!"
  - ECHO "BUILDING WHEELS..."
  - "%PYTHON%/python setup.py sdist bdist_wheel --plat-name=%PLAT_NAME% --python-tag=%PY_TAG%"
  - ps: rm dist/*.egg

artifacts:
  - path: dist\*
    name: pypiartifacts

